create database DB_INSTITUTE_OF_FINE_ARTS

--*********************Institue of Fine Arts Database*********************

--****************Adminlogin****************

CREATE TABLE ADMIN_LOGIN(
    AD_ID INT IDENTITY(1,1) NOT NULL,
    AD_NAME NVARCHAR(50) NOT NULL,
    AD_PASSWORD NVARCHAR(50) NOT NULL,
    AD_PROFILE NVARCHAR(MAX) NOT NULL,
)

--****************Students****************

CREATE TABLE STUDENT_LOGIN(
    STDL_ID INT IDENTITY(1,1) NOT NULL,
    STDL_NAME NVARCHAR(50) NOT NULL,
    STDL_PASSWORD NVARCHAR(50) NOT NULL,
    STDL_PROFILE NVARCHAR(MAX) NOT NULL,
)

--****************Student Detials****************

CREATE TABLE STUDENT_DETAILS(
    SD_STDL_ID INT NOT NULL,
    STD_ADDRESS NVARCHAR(200) NULL,
    STD_EMAIL NVARCHAR(100) NULL,
    STD_PHONE NVARCHAR(50) NOT NULL,
    STD_DATE_OF_BIRTH DATE NOT NULL
)

--****************Staff****************

CREATE TABLE STAFF_LOGIN (
    STF_ID INT IDENTITY(1,1) NOT NULL,
    STF_NAME NVARCHAR(50) NOT NULL,
    STF_PASSWORD NVARCHAR(50) NOT NULL,
    STF_PROFILE NVARCHAR(MAX) NOT NULL
)

--****************Staff Detials****************

CREATE TABLE STAFF_DETAILS(
    STFD_ID INT NOT NULL,
    STFD_EDUCATION NVARCHAR(200) NOT NULL,
    STFD_ADDRESS NVARCHAR(200) NULL,
    STFD_EMAIL NVARCHAR(100) NULL,
    STFD_PHONE NVARCHAR(50) NOT NULL,
    STFD_DATE_OF_BIRTH DATE NOT NULL,
    STFD_SALARY DECIMAL(10,2) NULL
)

--****************Compitition****************

CREATE TABLE COMPITITION (
    COM_ID INT IDENTITY(1,1) NOT NULL,
    COM_NAME NVARCHAR(50) UNIQUE NOT NULL,
    COM_START_DATE DATETIME NOT NULL,
    COM_END_DATE DATETIME NOT NULL,
    COM_STF_ID INT NOT NULL
)

--****************Work of Compition****************

CREATE TABLE WORK_OF_COMPITITION (
    WOC_ID INT NOT NULL,
    WOC_REG_ID INT NOT NULL,
    WOC_COM_ID INT NOT NULL,
    WOC_WORK NVARCHAR(MAX) NOT NULL
)

--****************Courses****************

CREATE TABLE COURSES (
    CR_ID INT IDENTITY(1,1) NOT NULL,
    CR_NAME NVARCHAR(20) UNIQUE NOT NULL,
)

--****************Core tables****************

--****************Registration****************

CREATE TABLE REGISTRATION (
    REG_ID INT IDENTITY(1,1) NOT NULL,
    REG_STDL_ID INT NOT NULL,
    REG_CR_ID INT NULL,
    REG_DATE DATE NOT NULL
)

--****************Assigned****************

CREATE TABLE ASSIGNED (
	ASI_ID INT IDENTITY(1,1) NOT NULL,
	ASI_STFL_ID INT NOT NULL,
	ASI_CR_ID INT NULL,
	ASI_DATE DATE NOT NULL    
)

--****************Administration****************

CREATE TABLE ADMINISTRATION (
	ADMIN_AD_ID INT NOT NULL,
    ADMIN_REG_ID INT NOT NULL,
    ADMIN_ASI_ID INT NOT NULL,
    ADMIN_COM_ID INT NOT NULL,
	ADMIN_RES_ID INT NOT NULL,
	ADMIN_EXI_ID INT NOT NULL
)

--****************Result****************

CREATE TABLE RESULT(
    RES_ID INT IDENTITY(1,1) NOT NULL,
	RES_COM_ID INT NOT NULL,
)

--****************Result detials****************

CREATE TABLE RESULT_ENTRIES (
    RES_ID INT NOT NULL,
	RES_WORK_ID INT NOT NULL,
    RES_MARKS DECIMAL(3, 2) NOT NULL,
    RES_DATE DATETIME NOT NULL,
    RES_GRADE CHAR(2) NOT NULL,
	RES_IS_ELIGIBLE BIT DEFAULT 0 
)

--****************Exibition****************

CREATE TABLE EXIBITION (
    EXB_ID INT IDENTITY(1,1) NOT NULL,
    EXB_NAME NVARCHAR(50) NOT NULL,
    EXB_START_DATE DATETIME NOT NULL,
    EXB_END_DATE DATETIME NOT NULL,
)

--****************Exibition Entries****************

CREATE TABLE EXIBITION_ENTRIES (
    EXB_EN_EXB_ID INT NOT NULL,
	EXB_EN_RES_ID INT NOT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
)

--****************PRIMARY KEYS****************

ALTER TABLE ADMIN_LOGIN
    ADD CONSTRAINT PK_ADMIN_LOGIN PRIMARY KEY (AD_ID)

ALTER TABLE STUDENT_LOGIN
    ADD CONSTRAINT PK_STUDENT_LOGIN PRIMARY KEY (STDL_ID)

ALTER TABLE STAFF_LOGIN
    ADD CONSTRAINT PK_STAFF_LOGIN PRIMARY KEY (STF_ID)

ALTER TABLE COMPITITION
    ADD CONSTRAINT PK_COMPITITION PRIMARY KEY (COM_ID)

ALTER TABLE COURSES
    ADD CONSTRAINT PK_COURSES PRIMARY KEY (CR_ID)
  
ALTER TABLE REGISTRATION
    ADD CONSTRAINT PK_REGISTRATION PRIMARY KEY (REG_ID)
  
ALTER TABLE ASSIGNED
    ADD CONSTRAINT PK_ASSIGNED PRIMARY KEY (ASI_ID)
  
ALTER TABLE WORK_OF_COMPITITION
    ADD CONSTRAINT PK_WORK_OF_COMPITITION PRIMARY KEY (WOC_ID)
  
ALTER TABLE RESULT
    ADD CONSTRAINT PK_RESULT PRIMARY KEY (RES_ID)
  
ALTER TABLE EXIBITION
    ADD CONSTRAINT PK_EXIBITION PRIMARY KEY (EXB_ID)

--****************FORIGNE KEYS****************

ALTER TABLE STUDENT_DETAILS
    ADD CONSTRAINT FK_STUDENT_DETIALS_TO_STUDENT_LOGIN
    FOREIGN KEY (SD_STDL_ID) REFERENCES STUDENT_LOGIN (STDL_ID) ON DELETE CASCADE ON UPDATE CASCADE
 
ALTER TABLE STAFF_DETAILS
    ADD CONSTRAINT FK_STAFF_DETIALS_TO_STAFF_LOGIN
    FOREIGN KEY (STFD_ID) REFERENCES STAFF_LOGIN (STF_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE COMPITITION
    ADD CONSTRAINT FK_STAFF_LOGIN_TO_COMPITITION 
    FOREIGN KEY (COM_STF_ID) REFERENCES STAFF_LOGIN (STF_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE REGISTRATION
    ADD CONSTRAINT FK_REGISTRATION_TO_STUDENT_LOGIN 
    FOREIGN KEY (REG_STDL_ID) REFERENCES STUDENT_LOGIN (STDL_ID) ON DELETE CASCADE ON UPDATE CASCADE
    
ALTER TABLE REGISTRATION
    ADD CONSTRAINT FK_REGISTRATION_TO_COURSES 
    FOREIGN KEY (REG_CR_ID) REFERENCES COURSES (CR_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE ASSIGNED
    ADD CONSTRAINT FK_ASSIGNED_TO_STAFF_LOGIN 
    FOREIGN KEY (ASI_STFL_ID) REFERENCES STAFF_LOGIN (STF_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE ASSIGNED
    ADD CONSTRAINT FK_ASSIGNED_TO_COURSES 
    FOREIGN KEY (ASI_CR_ID) REFERENCES COURSES (CR_ID) ON DELETE CASCADE ON UPDATE CASCADE

--********** removed
--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_ADMIN_LOGIN
--    FOREIGN KEY (ADMIN_AD_ID) REFERENCES ADMIN_LOGIN (AD_ID)

--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_REGISTRATION 
--    FOREIGN KEY (ADMIN_REG_ID) REFERENCES REGISTRATION (REG_ID)

--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_ASSIGNED 
--    FOREIGN KEY (ADMIN_ASI_ID) REFERENCES ASSIGNED (ASI_ID) 

--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_COMPITITION
--    FOREIGN KEY (ADMIN_COM_ID) REFERENCES COMPITITION (COM_ID)

--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_RESULT 
--    FOREIGN KEY (ADMIN_RES_ID) REFERENCES RESULT (RES_ID) 

--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_EXIBITION
--    FOREIGN KEY (ADMIN_EXI_ID) REFERENCES EXIBITION (EXB_ID)

--	--CONFLICT
--ALTER TABLE ADMINISTRATION
--    ADD CONSTRAINT FK_ADMINISTRATION_TO_COMPITITION 
--    FOREIGN KEY (ADMIN_COM_ID) REFERENCES COMPITITION (COM_ID) 
--	--END
--ALTER TABLE ADMINISTRATION
--    drop CONSTRAINT FK_ADMINISTRATION_TO_CONTACT 
--    FOREIGN KEY (ADMIN_CON_ID) REFERENCES  CONTACT (CON_ID)

ALTER TABLE WORK_OF_COMPITITION
    ADD CONSTRAINT FK_WORK_OF_COMPITITION_TO_REGISTRATION 
    FOREIGN KEY (WOC_REG_ID) REFERENCES REGISTRATION (REG_ID)

ALTER TABLE WORK_OF_COMPITITION
    ADD CONSTRAINT FK_WORK_OF_COMPITITION_TO_COMPITITION
    FOREIGN KEY (WOC_COM_ID) REFERENCES COMPITITION (COM_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE RESULT
    ADD CONSTRAINT FK_RESULT_TO_COMPITITION 
    FOREIGN KEY (RES_COM_ID) REFERENCES COMPITITION (COM_ID) ON DELETE CASCADE ON UPDATE CASCADE
        

ALTER TABLE RESULT_ENTRIES
    ADD CONSTRAINT FK_RESULT_ENTRIES_TO_RESULT
    FOREIGN KEY (RES_ID) REFERENCES RESULT (RES_ID) ON DELETE CASCADE ON UPDATE CASCADE


ALTER TABLE RESULT_ENTRIES
    ADD CONSTRAINT FK_RESULT_TO_WORK_OF_COMPITITION 
    FOREIGN KEY (RES_WORK_ID) REFERENCES WORK_OF_COMPITITION (WOC_ID)

ALTER TABLE EXIBITION_ENTRIES
    ADD CONSTRAINT FK_EXIBITION_TO_REGISTRATION
    FOREIGN KEY (EXB_EN_RES_ID) REFERENCES  REGISTRATION (REG_ID) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE EXIBITION_ENTRIES
    ADD CONSTRAINT FK_EXIBITION_TO_EXIBITION
    FOREIGN KEY (EXB_EN_EXB_ID) REFERENCES  EXIBITION (EXB_ID) ON DELETE CASCADE ON UPDATE CASCADE


ALTER TABLE ADMIN_LOGIN
     ADD _ADID INT IDENTITY(1,1) NOT NULL

ALTER TABLE MANAGER_LOGIN
     ADD _MALID INT IDENTITY(1,1) NOT NULL

ALTER TABLE CONTACT
     ADD _CONID INT IDENTITY(1,1) NOT NULL

ALTER TABLE FEEDBACK
     ADD _FEDID INT IDENTITY(1,1) NOT NULL

ALTER TABLE STUDENT_LOGIN
     ADD _STLID INT IDENTITY(1,1) NOT NULL

ALTER TABLE STAFF_LOGIN
     ADD _STDID INT IDENTITY(1,1) NOT NULL

ALTER TABLE COMPITITION
     ADD _COMID INT IDENTITY(1,1) NOT NULL

ALTER TABLE PROGRAM
     ADD _PROID INT IDENTITY(1,1) NOT NULL
 
ALTER TABLE COURSES
     ADD _COUID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE REGISTRATION
     ADD _RESID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE ASSIGNED
     ADD _ASIID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE WORK_OF_COMPITITION
     ADD _WORID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE ATTENDENCE
     ADD _ATTID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE RESULT
     ADD _REUID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE SCHOLARSHIP
     ADD _SCOID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE FAILED_PROJECTS
     ADD _FAPID INT IDENTITY(1,1) NOT NULL

ALTER TABLE EXIBITION
     ADD _EXIID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE FEES
     ADD _FEEID INT IDENTITY(1,1) NOT NULL
  
ALTER TABLE DEFAULTER
     ADD _DEFID INT IDENTITY(1,1) NOT NULL




ALTER TABLE ADMIN_LOGIN
     DROP COLUMN _ADID  

ALTER TABLE MANAGER_LOGIN
     DROP COLUMN _MALID 

ALTER TABLE CONTACT
     DROP COLUMN _CONID 

ALTER TABLE FEEDBACK
     DROP COLUMN _FEDID 

ALTER TABLE STUDENT_LOGIN
     DROP COLUMN _STLID 

ALTER TABLE STAFF_LOGIN
     DROP COLUMN _STDID 

ALTER TABLE COMPITITION
     DROP COLUMN _COMID 

ALTER TABLE PROGRAM
     DROP COLUMN _PROID 
 
ALTER TABLE COURSES
     DROP COLUMN _COUID 
  
ALTER TABLE REGISTRATION
     DROP COLUMN _RESID 
  
ALTER TABLE ASSIGNED
     DROP COLUMN _ASIID 
  
ALTER TABLE WORK_OF_COMPITITION
     DROP COLUMN _WORID 
  
ALTER TABLE ATTENDENCE
     DROP COLUMN _ATTID 
  
ALTER TABLE RESULT
     DROP COLUMN _REUID 
  
ALTER TABLE SCHOLARSHIP
     DROP COLUMN _SCOID 
  
ALTER TABLE FAILED_PROJECTS
     DROP COLUMN _FAPID 
     
ALTER TABLE EXIBITION
     DROP COLUMN _EXIID 
  
ALTER TABLE FEES
     DROP COLUMN _FEEID 
  
ALTER TABLE DEFAULTER
     DROP COLUMN _DEFID 

ALTER TABLE ADMIN_LOGIN
   ADD AD_ID NVARCHAR(20) NOT NULL    

ALTER TABLE MANAGER_LOGIN
   ADD MG_ID NVARCHAR(20) NOT NULL   

ALTER TABLE CONTACT
   ADD CON_ID NVARCHAR(20) NOT NULL   

ALTER TABLE FEEDBACK
   ADD FDB_ID NVARCHAR(20) NOT NULL   

ALTER TABLE STUDENT_LOGIN
   ADD STDL_ID NVARCHAR(20) NOT NULL  

ALTER TABLE STAFF_LOGIN
   ADD STF_ID NVARCHAR(20) NOT NULL   

ALTER TABLE COMPITITION
   ADD COM_ID NVARCHAR(20) NOT NULL   

ALTER TABLE PROGRAM
   ADD PR_ID NVARCHAR(20) NOT NULL   
 
ALTER TABLE COURSES
   ADD CR_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE REGISTRATION
   ADD REG_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE ASSIGNED
   ADD ASI_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE WORK_OF_COMPITITION
   ADD WOC_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE ATTENDENCE
   ADD ATD_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE RESULT
   ADD RES_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE SCHOLARSHIP
   ADD SCR_ID NVARCHAR(20) NOT NULL   
  
ALTER TABLE FAILED_PROJECTS
   ADD FP_ID NVARCHAR(20) NOT NULL  

ALTER TABLE EXIBITION
   ADD EXB_ID NVARCHAR(20) NOT NULL   

ALTER TABLE FEES
   ADD FS_ID NVARCHAR(20) NOT NULL   

ALTER TABLE DEFAULTER
   ADD DEF_ID NVARCHAR(20) NOT NULL   



ALTER TABLE ADMIN_LOGIN
    DROP COLUMN AD_ID

ALTER TABLE MANAGER_LOGIN
    DROP COLUMN MG_ID

ALTER TABLE CONTACT
    DROP COLUMN CON_ID

ALTER TABLE FEEDBACK
    DROP COLUMN FDB_ID

ALTER TABLE STUDENT_LOGIN
    DROP COLUMN STDL_ID

ALTER TABLE STAFF_LOGIN
    DROP COLUMN STF_ID

ALTER TABLE COMPITITION
    DROP COLUMN COM_ID

ALTER TABLE PROGRAM
    DROP COLUMN PR_ID
 
ALTER TABLE COURSES
    DROP COLUMN CR_ID
  
ALTER TABLE REGISTRATION
    DROP COLUMN REG_ID
  
ALTER TABLE ASSIGNED
    DROP COLUMN ASI_ID
  
ALTER TABLE WORK_OF_COMPITITION
    DROP COLUMN WOC_ID
  
ALTER TABLE ATTENDENCE
    DROP COLUMN ATD_ID
  
ALTER TABLE RESULT
    DROP COLUMN RES_ID
  
ALTER TABLE SCHOLARSHIP
    DROP COLUMN SCR_ID
  
ALTER TABLE FAILED_PROJECTS
    DROP COLUMN FP_ID
  
ALTER TABLE EXIBITION
    DROP COLUMN EXB_ID
  
ALTER TABLE FEES
    DROP COLUMN FS_ID
  
ALTER TABLE DEFAULTER
    DROP COLUMN DEF_ID
  

ALTER TABLE ADMIN_LOGIN        
DROP CONSTRAINT PK_ADMIN_LOGIN            
ALTER TABLE MANAGER_LOGIN      
DROP CONSTRAINT PK_MANAGER_LOGIN          
ALTER TABLE CONTACT            
DROP CONSTRAINT PK_CONTACT                
ALTER TABLE FEEDBACK           
DROP CONSTRAINT PK_FEEDBACK               
ALTER TABLE STUDENT_LOGIN      
DROP CONSTRAINT PK_STUDENT_LOGIN          
ALTER TABLE STAFF_LOGIN        
DROP CONSTRAINT PK_STAFF_LOGIN            
ALTER TABLE COMPITITION        
DROP CONSTRAINT PK_COMPITITION            
ALTER TABLE PROGRAM            
DROP CONSTRAINT PK_PROGRAM                
ALTER TABLE COURSES            
DROP CONSTRAINT PK_COURSES                
ALTER TABLE REGISTRATION       
DROP CONSTRAINT PK_REGISTRATION           
ALTER TABLE ASSIGNED           
DROP CONSTRAINT PK_ASSIGNED               
ALTER TABLE WORK_OF_COMPITITION
DROP CONSTRAINT PK_WORK_OF_COMPITITION    
ALTER TABLE ATTENDENCE         
DROP CONSTRAINT PK_ATTENDENCE             
ALTER TABLE RESULT             
DROP CONSTRAINT PK_RESULT                 
ALTER TABLE SCHOLARSHIP        
DROP CONSTRAINT PK_SCHOLARSHIP            
ALTER TABLE FAILED_PROJECTS    
DROP CONSTRAINT PK_FAILED_PROJECTS        
ALTER TABLE EXIBITION          
DROP CONSTRAINT PK_EXIBITION              
ALTER TABLE FEES               
DROP CONSTRAINT PK_FEES                   
ALTER TABLE DEFAULTER          
DROP CONSTRAINT PK_DEFAULTER              


DROP TABLE ADMIN_LOGIN       
DROP TABLE ADMINISTRATION
DROP TABLE STUDENT_LOGIN 
DROP TABLE STUDENT_DETAILS
DROP TABLE STAFF_LOGIN                 
DROP TABLE STAFF_DETAILS
DROP TABLE COMPITITION                                            
DROP TABLE COURSES                        
DROP TABLE REGISTRATION              
DROP TABLE ASSIGNED                      
DROP TABLE WORK_OF_COMPITITION                 
DROP TABLE RESULT    
DROP TABLE RESULT_ENTRIES
DROP TABLE EXIBITION                     
DROP TABLE EXIBITION_ENTRIES