--*********************Institue of Fine Arts Database*************

--*********************Populate	studdent id id in registration table*********************


CREATE TRIGGER TR_POPULATE_REGISTRATION_DETIALS_BY_STUDENT
ON STUDENT_LOGIN
AFTER INSERT 
AS
BEGIN
  IF EXISTS(SELECT STDL_ID FROM INSERTED)
      BEGIN
		  DECLARE @MAINID VARCHAR(20)
		  SET @MAINID = (SELECT STDL_ID FROM INSERTED)
		  INSERT INTO REGISTRATION(REG_ID,REG_STDL_ID,REG_DATE) SELECT @MAINID , GETDATE() 
	  END
END
GO

--*********************Populate	STAFF id id in ASSIGNED table*********************


CREATE TRIGGER TR_POPULATE_ASSIGEND_DETIALS_BY_STAFF
ON STAFF_LOGIN 
AFTER INSERT , DELETE
AS
BEGIN
  IF EXISTS(SELECT STF_ID FROM INSERTED)
      BEGIN
		  DECLARE @MAINID VARCHAR(20)
		  SET @MAINID = (SELECT STF_ID FROM INSERTED)
		  INSERT INTO ASSIGNED(ASI_ID,ASI_STFL_ID,ASI_DATE) SELECT  @MAINID , GETDATE() 
	  END
END
GO

CREATE TRIGGER TR_POPULATE_RESULTS_BY_COMPITITION
ON COMPITITION 
AFTER INSERT , DELETE
AS
BEGIN
  IF EXISTS(SELECT COM_ID FROM INSERTED)
      BEGIN
		  DECLARE @MAINID VARCHAR(20)
		  SET @MAINID = (SELECT COM_ID FROM INSERTED)
		  INSERT INTO RESULT(RES_COM_ID) SELECT  @MAINID 
	  END
END
GO

SELECT * FROM VW_FEES
SELECT * FROM VW_DEFAULTER

UPDATE FEES SET FS_LAST_DATE = '2021-05-01'
UPDATE FEES SET FS_PAID = 0


SELECT * FROM RESULT

SELECT * FROM VW_ADMIN_LOGIN
SELECT * FROM VW_ADMINISTRATION
SELECT * FROM VW_STUDENT_LOGIN
SELECT * FROM REGISTRATION


drop TRIGGER TR_POPULATE_ADMINSTRATION_BY_REGESTRATION

drop TRIGGER TR_POPULATE_ADMINSTRATION_BY_ASSIGNED

drop TRIGGER TR_POPULATE_ADMINSTRATION_BY_COMPITITION

drop TRIGGER TR_POPULATE_ADMINSTRATION_BY_CONTACT

drop TRIGGER TR_POPULATE_REGISTRATION_DETIALS_BY_STUDENT

drop TRIGGER TR_POPULATE_ASSIGEND_DETIALS_BY_STAFF

drop TRIGGER TR_POPULATE_FAILED_PROJECT_FROM_RESULT

drop TRIGGER TR_POPULATE_DEFAULTER_FROM_FEES

drop TRIGGER TR_POPULATE_DEFAULTER_FROM_FEES

drop TRIGGER TR_POPULATE_MANAGER_BY_EXIBITION

drop TRIGGER TR_POPULATE_MANAGER_BY_FEEDBACK

drop TRIGGER TR_POPULATE_SCHOLARSHIP_BY_RESULT

drop TRIGGER TR_POPULATE_ATTENDENCE_BY_WORK_OF_COMPITITION
