--*********************Institue of Fine Arts Database*********************

--****************Table view for taking all of the data****************

--****************Adminlogin****************

CREATE VIEW VW_ADMIN_LOGIN
AS
SELECT * FROM ADMIN_LOGIN
GO
--****************Student Detials****************

CREATE VIEW VW_STUDENT_DETAILS
AS
SELECT * FROM STUDENT_DETAILS
GO
--****************Staff Detials****************

CREATE VIEW VW_STAFF_DETAILS
AS
SELECT * FROM STAFF_DETAILS 
GO

--****************Students****************

CREATE VIEW VW_STUDENT_LOGIN
AS
SELECT * FROM STUDENT_LOGIN    
GO

--****************Staff****************

CREATE VIEW VW_STAFF_LOGIN 
AS
SELECT * FROM STAFF_LOGIN    
GO

--****************Compitition****************

CREATE VIEW VW_COMPITITION 
AS
SELECT * FROM COMPITITION   
GO

--****************Courses****************

CREATE VIEW VW_COURSES 
AS
SELECT * FROM COURSES    
GO

--****************Registration****************

CREATE VIEW VW_REGISTRATION 
AS
SELECT * FROM REGISTRATION    
GO
    
    

--****************Assigned****************

CREATE VIEW VW_ASSIGNED 
AS
SELECT * FROM ASSIGNED    
GO
          

--****************Work of Compition****************

CREATE VIEW VW_WORK_OF_COMPITITION 
AS
SELECT * FROM WORK_OF_COMPITITION   
GO
     
--****************Result****************

CREATE VIEW VW_RESULT 
AS
SELECT * FROM RESULT    
GO

CREATE VIEW VW_RESULT_ENTRIES
AS
SELECT * FROM RESULT_ENTRIES
GO

--****************Exibition****************

CREATE VIEW VW_EXIBITION 
AS
SELECT * FROM EXIBITION    
GO



--****************Table data showing data in tables in application using joins etc****************

--****************ADMIN VIEW FOR VIEWING DATA****************

CREATE VIEW VW_SHOW_STUDENTS_ALL_DATA 
AS
SELECT VW_SL.*,VW_SD.*,RE.* FROM VW_STUDENT_LOGIN VW_SL INNER JOIN 
VW_STUDENT_DETAILS VW_SD ON VW_SL.STDL_ID = VW_SD.SD_STDL_ID
INNER JOIN VW_REGISTRATION RE ON RE.REG_STDL_ID = VW_SL.STDL_ID
GO

select * from VW_SHOW_STUDENTS_ALL_DATA


CREATE VIEW VW_SHOW_STUDENTS_ALL_DETIALS 
AS
SELECT VW_SL.*,VW_SD.* FROM VW_STUDENT_LOGIN VW_SL INNER JOIN 
VW_STUDENT_DETAILS VW_SD ON VW_SL.STDL_ID = VW_SD.SD_STDL_ID
GO

SELECT * FROM VW_SHOW_STUDENTS_ALL_DETIALS

select * from VW_COURSES

--EXEC SP_COURSES
--select * from VW_SHOW_STUDENTS_ALL_DATA

CREATE VIEW VW_SHOW_STAFF_ALL_DATA
AS
SELECT VW_STFL.*,VW_STFD.*,ASD.* FROM VW_STAFF_LOGIN VW_STFL INNER JOIN 
VW_STAFF_DETAILS VW_STFD ON VW_STFL.STF_ID = VW_STFD.STFD_ID
INNER JOIN VW_ASSIGNED ASD ON ASD.ASI_STFL_ID = VW_STFL.STF_ID
GO

CREATE VIEW VW_SHOW_STAFF_ALL_DETIALS
AS
SELECT VW_STFL.*,VW_STFD.* FROM VW_STAFF_LOGIN VW_STFL INNER JOIN 
VW_STAFF_DETAILS VW_STFD ON VW_STFL.STF_ID = VW_STFD.STFD_ID
GO
select * from VW_SHOW_STAFF_ALL_DATA

CREATE VIEW VW_SHOW_COMPITITION_ALL_DATA
AS
SELECT VW_COMP.*,VW_WC.*,
VW_STFL.STF_ID,VW_STFL.STF_NAME,VW_STFL.STF_PROFILE
FROM VW_STAFF_LOGIN VW_STFL INNER JOIN VW_COMPITITION VW_COMP ON VW_STFL.STF_ID = VW_COMP.COM_STF_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WC ON VW_COMP.COM_ID = VW_WC.WOC_COM_ID 
GO

--CREATE VIEW VW_SHOW_RESULT_ALL_DATA
--AS
--SELECT VW_STDL.STDL_ID,VW_STDL.STDL_NAME , VW_COMP.COM_NAME, VW_WO.WOC_WORK,VW_RES.*
--FROM VW_COMPITITION VW_COMP INNER JOIN
--VW_RESULT VW_RES ON VW_COMP.COM_ID = VW_RES.RES_COM_ID INNER JOIN VW_REGISTRATION RE ON
--VW_RESULT_ENTRIES. = RE.REG_ID INNER JOIN VW_STUDENT_LOGIN VW_STDL ON RE.REG_STDL_ID = VW_STDL.STDL_ID
--INNER JOIN VW_WORK_OF_COMPITITION VW_WO ON VW_WO.WOC_COM_ID = VW_COMP.COM_ID
--GO

CREATE VIEW VW_SHOW_RESULT_ALL_DATA
AS
SELECT STL.STDL_ID,STL.STDL_NAME , COM.COM_NAME, WCOM.WOC_WORK,RESE.*
FROM VW_RESULT_ENTRIES RESE INNER JOIN VW_RESULT RES ON RESE.RES_ID = RES.RES_ID
INNER JOIN VW_WORK_OF_COMPITITION WCOM ON RES.RES_COM_ID = WCOM.WOC_COM_ID
INNER JOIN VW_REGISTRATION RE ON WCOM.WOC_REG_ID = RE.REG_ID
INNER JOIN VW_STUDENT_LOGIN STL ON RE.REG_STDL_ID = STL.STDL_ID
INNER JOIN VW_COMPITITION COM ON COM.COM_ID = RES.RES_COM_ID
GO


select * from VW_SHOW_RESULT_ALL_DATA


CREATE VIEW VW_SHOW_ALL_EXIBITION_DATA
AS
SELECT EXBE.*,EXE.*,WOC.WOC_WORK,STDL.STDL_NAME,STDL.STDL_PROFILE,STDD.STD_EMAIL FROM EXIBITION_ENTRIES EXBE
INNER JOIN EXIBITION EXE ON EXE.EXB_ID = EXBE.EXB_EN_EXB_ID
INNER JOIN REGISTRATION REG ON REG.REG_ID = EXBE.EXB_EN_RES_ID
INNER JOIN STUDENT_LOGIN STDL ON  STDL.STDL_ID = REG.REG_STDL_ID
INNER JOIN STUDENT_DETAILS STDD ON STDD.SD_STDL_ID = STDL.STDL_ID
INNER JOIN WORK_OF_COMPITITION WOC ON WOC.WOC_REG_ID = REG.REG_ID
GO

--****************STUDENT VIEW FOR VIEWING DATA****************

CREATE VIEW VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE
AS
SELECT VW_SL.*,VW_STD.*,RE.* FROM VW_STUDENT_LOGIN VW_SL INNER JOIN 
VW_STUDENT_DETAILS VW_STD ON VW_SL.STDL_ID = VW_STD.SD_STDL_ID
INNER JOIN VW_REGISTRATION RE ON RE.REG_STDL_ID = VW_SL.STDL_ID
GO


CREATE VIEW VW_SHOW_COMPITION_ALL_DATA_FROM_STUDENT_SIDE
AS
SELECT VW_COMP.*,VW_WC.*,VW_STFL.STF_NAME,VW_STFL.STF_PROFILE
FROM VW_STAFF_LOGIN VW_STFL INNER JOIN VW_COMPITITION VW_COMP ON VW_STFL.STF_ID = VW_COMP.COM_STF_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WC ON VW_COMP.COM_ID = VW_WC.WOC_COM_ID 
GO

CREATE VIEW VW_SHOW_EXIBITION_ALL_DATA_FROM_STUDENT_SIDE
AS
SELECT VW_EX.*,VW_STDL.STDL_ID,VW_STDL.STDL_NAME,VW_COM.COM_ID,
VW_COM.COM_NAME,VW_COM.COM_AWARD,VW_COM.COM_FORMAT,VW_WOC.*,VW_ATD.*,VW_SCO.*
FROM VW_EXIBITION VW_EX 
INNER JOIN VW_SCHOLARSHIP VW_SCO ON VW_EX.EXB_SCR_ID = VW_SCO.SCR_ID
INNER JOIN VW_RESULT VW_RES ON VW_RES.RES_ID = VW_SCO.SCR_RES_ID
INNER JOIN VW_REGISTRATION RE ON RE.REG_ID = VW_RES.RES_ID
INNER JOIN VW_ATTENDENCE VW_ATD ON VW_ATD.ATD_REG_ID = RE.REG_ID
INNER JOIN VW_COMPITITION VW_COM ON VW_COM.COM_ID = VW_RES.RES_COM_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WOC ON VW_WOC.WOC_COM_ID = VW_COM.COM_ID
INNER JOIN VW_STUDENT_LOGIN VW_STDL ON VW_STDL.STDL_ID = RE.REG_STDL_ID
GO

CREATE VIEW VW_SHOW_FEES_ALL_DATA_STUDENT_SIDE
AS
SELECT VW_FE.*,VW_STDL.STDL_ID,VW_STDL.STDL_NAME,VW_STDL.STDL_PROFILE
FROM VW_FEES VW_FE 
INNER JOIN VW_REGISTRATION RE ON RE.REG_ID = VW_FE.FS_REG_ID
INNER JOIN VW_STUDENT_LOGIN VW_STDL ON VW_STDL.STDL_ID = RE.REG_STDL_ID
GO

--****************Staff VIEW FOR VIEWING DATA****************

CREATE VIEW VW_SHOW_STAFF_ALL_DATA_FROM_STAFF
AS
SELECT VW_STFL.*,VW_STFD.*,ASD.* FROM VW_STAFF_LOGIN VW_STFL INNER JOIN 
VW_STAFF_DETAILS VW_STFD ON VW_STFL.STF_ID = VW_STFD.ST_STFD_ID
INNER JOIN VW_ASSIGNED ASD ON ASD.ASI_STFL_ID = VW_STFL.STF_ID
GO

CREATE VIEW VW_SHOW_COMPITITION_ALL_DATA_FROM_STAFF
AS
SELECT VW_COMP.*,VW_WC.*,
VW_STFL.STF_ID,VW_STFL.STF_NAME,VW_STFL.STF_PROFILE
FROM VW_STAFF_LOGIN VW_STFL INNER JOIN VW_COMPITITION VW_COMP ON VW_STFL.STF_ID = VW_COMP.COM_STF_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WC ON VW_COMP.COM_ID = VW_WC.WOC_COM_ID 
GO

CREATE VIEW VW_SHOW_STUDENTS_ALL_DATA_FROM_STAFF
AS
SELECT VW_SL.*,VW_SD.*,RE.*,VW_CO.* 
FROM VW_STUDENT_LOGIN VW_SL INNER JOIN 
VW_STUDENT_DETAILS VW_SD ON VW_SL.STDL_ID = VW_SD.SD_STDL_ID
INNER JOIN VW_REGISTRATION RE ON RE.REG_STDL_ID = VW_SL.STDL_ID
INNER JOIN VW_COURSES VW_CO ON VW_CO.CR_ID = RE.REG_CR_ID
INNER JOIN VW_ASSIGNED VW_AS ON VW_AS.ASI_CR_ID = VW_CO.CR_ID
INNER JOIN VW_STAFF_LOGIN VW_STFL ON VW_STFL.STF_ID = VW_AS.ASI_STFL_ID
GO


CREATE VIEW VW_SHOW_RESULT_ALL_DATA_FROM_STAFF
AS
SELECT VW_STDL.STDL_ID,VW_STDL.STDL_NAME , VW_COMP.COM_NAME, VW_WO.WOC_WORK,VW_RES.*,VW_CO.*
FROM VW_COMPITITION VW_COMP INNER JOIN
VW_RESULT VW_RES ON VW_COMP.COM_ID = VW_RES.RES_COM_ID INNER JOIN VW_REGISTRATION RE ON
VW_RES.RES_RES_ID = RE.REG_ID INNER JOIN VW_STUDENT_LOGIN VW_STDL ON RE.REG_STDL_ID = VW_STDL.STDL_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WO ON VW_WO.WOC_COM_ID = VW_COMP.COM_ID
INNER JOIN VW_SCHOLARSHIP CW_SCO ON CW_SCO.SCR_RES_ID = VW_RES.RES_ID
INNER JOIN VW_FAILED_PROJECTS VW_FP ON VW_FP.FP_RES_ID = VW_RES.RES_ID
INNER JOIN VW_COURSES VW_CO ON VW_CO.CR_ID = RE.REG_CR_ID
INNER JOIN VW_ASSIGNED VW_AS ON VW_AS.ASI_CR_ID = VW_CO.CR_ID
GO

--****************MANAGER VIEW FOR VIEWING DATA****************

CREATE VIEW VW_SHOW_EXIBITION_ALL_DATA_FROM_MANAGER_SIDE
AS
SELECT VW_EX.*,VW_STDL.STDL_ID,VW_STDL.STDL_NAME,VW_COM.COM_ID,
VW_COM.COM_NAME,VW_COM.COM_AWARD,VW_COM.COM_FORMAT,VW_WOC.*,VW_ATD.*,VW_SCO.*
FROM VW_EXIBITION VW_EX 
INNER JOIN VW_SCHOLARSHIP VW_SCO ON VW_EX.EXB_SCR_ID = VW_SCO.SCR_ID
INNER JOIN VW_RESULT VW_RES ON VW_RES.RES_ID = VW_SCO.SCR_RES_ID
INNER JOIN VW_REGISTRATION RE ON RE.REG_ID = VW_RES.RES_ID
INNER JOIN VW_ATTENDENCE VW_ATD ON VW_ATD.ATD_REG_ID = RE.REG_ID
INNER JOIN VW_COMPITITION VW_COM ON VW_COM.COM_ID = VW_RES.RES_COM_ID
INNER JOIN VW_WORK_OF_COMPITITION VW_WOC ON VW_WOC.WOC_COM_ID = VW_COM.COM_ID
INNER JOIN VW_STUDENT_LOGIN VW_STDL ON VW_STDL.STDL_ID = RE.REG_STDL_ID	
INNER JOIN VW_MANAGER VW_MANG ON VW_MANG.MG_EXB_ID = VW_EX.EXB_ID
INNER JOIN VW_MANAGER_LOGIN ML ON ML.MG_ID = VW_MANG.MG_MGL_ID
GO

CREATE VIEW VW_SHOW_FEEDBACK_ALL_DATA
AS
SELECT VW_FE.* 
FROM VW_FEEDBACK VW_FE
INNER JOIN VW_MANAGER VW_MANG ON VW_MANG.MG_FDB_ID = VW_FE.FDB_ID
INNER JOIN VW_MANAGER_LOGIN ML ON ML.MG_ID = VW_MANG.MG_MGL_ID
GO

--SHOW COMPITION DATA TO STUDENTS

CREATE VIEW VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS
AS
SELECT c.*,st.STF_NAME,cr.CR_ID,cr.CR_NAME from COMPITITION c 
INNER JOIN ASSIGNED s ON c.COM_STF_ID = s.ASI_STFL_ID
INNER JOIN STAFF_LOGIN st ON st.STF_ID = s.ASI_STFL_ID
INNER JOIN COURSES cr ON cr.CR_ID = s.ASI_CR_ID
GO

DELETE VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS
--SHOW RESULT IN CARD

CREATE VIEW VW_SHOW_RESULT_CARD_DETIALS
AS
SELECT RES.RES_ID , COM.* , STFL.STF_NAME FROM RESULT RES 
INNER JOIN COMPITITION COM ON COM.COM_ID = RES.RES_COM_ID
INNER JOIN STAFF_LOGIN STFL ON STFL.STF_ID = COM.COM_STF_ID 
GO

INSERT INTO RESULT VALUES(5)

SELECT * FROM RESULT

SELECT * FROM VW_SHOW_RESULT_CARD_DETIALS

SELECT * FROM RESULT_ENTRIES

SELECT * FROM WORK_OF_COMPITITION

SELECT * FROM VW_SHOW_RESULT_ALL_DATA

SELECT * FROM VW_SHOW_RESULT_ALL_DATA_FROM_STAFF

select * from VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS

SELECT * FROM VW_PROGRAM
SELECT * FROM VW_COURSES
SELECT * FROM VW_STUDENT_LOGIN
SELECT * FROM VW_STUDENT_DETAILS
SELECT * FROM VW_REGISTRATION
SELECT * FROM VW_ADMINISTRATION
SELECT * FROM VW_STAFF_DETAILS
SELECT * FROM VW_STAFF_LOGIN
SELECT * FROM VW_STAFF_DETAILS
SELECT * FROM VW_ASSIGNED
SELECT * FROM VW_SHOW_RESULT_ALL_DATA
SELECT * FROM VW_SHOW_CONTACT_ALL_DATA

DELETE FROM VW_PROGRAM
DELETE FROM VW_COURSES
DELETE FROM VW_STUDENT_LOGIN
DELETE FROM VW_STUDENT_DETAILS
DELETE FROM VW_REGISTRATION
DELETE FROM VW_FEES
DELETE FROM VW_STAFF_LOGIN
DELETE FROM VW_STAFF_DETAILS

SELECT * FROM VW_SHOW_COMPITITION_ALL_DATA
SELECT * FROM VW_SHOW_STUDENTS_ALL_DATA
SELECT * FROM VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE
SELECT * FROM VW_SHOW_STUDENTS_ALL_DATA_FROM_STAFF
SELECT * FROM VW_SHOW_STAFF_ALL_DATA
SELECT * FROM VW_SHOW_RESULT_ALL_DATA
SELECT * FROM VW_SHOW_EXIBITION_ALL_DATA_FROM_STUDENT_SIDE
SELECT * FROM VW_SHOW_COMPITION_ALL_DATA_FROM_STUDENT_SIDE
SELECT * FROM VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE
SELECT * FROM VW_SHOW_FEES_ALL_DATA_STUDENT_SIDE


INSERT INTO VW_PROGRAM VALUES('P1','DD',2)
INSERT INTO VW_COURSES VALUES('CS1','DSSF',2,'P1')
INSERT INTO VW_SEMESTER VALUES('SEM1','BEG',2)

INSERT INTO VW_STUDENT_LOGIN VALUES('SDS1CS100','ASDAS','ASDAS','ASDASD')
INSERT INTO VW_STUDENT_DETAILS(STD_ADDRESS,STD_EMAIL,STD_PHONE,STD_DATE_OF_BIRTH) VALUES('SFSD','SDFSD','01115',GETDATE())
INSERT INTO VW_REGISTRATION VALUES ('RE1','SDS1CS100','CS1','SEM1',GETDATE())
INSERT INTO VW_ADMINISTRATION (ADMIN_REG_ID) VALUES ('RE1')
INSERT INTO VW_FEES VALUES ('FS100','REG1',1000.00,0,GETDATE()) 

SELECT * FROM VW_ADMINISTRATION

SELECT * FROM VW_REGISTRATION

SELECT * FROM ADMINISTRATION


DELETE FROM ADMINISTRATION
DELETE FROM REGISTRATION


DROP VIEW VW_ADMIN_LOGIN

DROP VIEW VW_MANAGER_LOGIN

DROP VIEW VW_STUDENT_DETAILS

DROP VIEW VW_STAFF_DETAILS

DROP VIEW VW_CONTACT 

DROP VIEW VW_FEEDBACK 

DROP VIEW VW_STUDENT_LOGIN

DROP VIEW VW_STAFF_LOGIN 

DROP VIEW VW_COMPITITION 

DROP VIEW VW_PROGRAM 

DROP VIEW VW_COURSES 

DROP VIEW VW_REGISTRATION 

DROP VIEW VW_ASSIGNED 

DROP VIEW VW_ADMINISTRATION 

DROP VIEW VW_WORK_OF_COMPITITION 

DROP VIEW VW_ATTENDENCE 

DROP VIEW VW_RESULT 

DROP VIEW VW_SCHOLARSHIP 

DROP VIEW VW_FAILED_PROJECTS 

DROP VIEW VW_EXIBITION 

DROP VIEW VW_MANAGER 

DROP VIEW VW_FEES 

DROP VIEW VW_DEFAULTER  

DROP VIEW VW_SHOW_STUDENTS_ALL_DATA 

DROP VIEW VW_SHOW_STAFF_ALL_DATA

DROP VIEW VW_SHOW_COMPITITION_ALL_DATA

DROP VIEW VW_SHOW_RESULT_ALL_DATA

DROP VIEW VW_SHOW_CONTACT_ALL_DATA

DROP VIEW VW_SHOW_FEES_ALL_DATA

DROP VIEW VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE

DROP VIEW VW_SHOW_COMPITION_ALL_DATA_FROM_STUDENT_SIDE

DROP VIEW VW_SHOW_RESULT_ALL_DATA_FROM_STUDENT_SIDE

DROP VIEW VW_SHOW_EXIBITION_ALL_DATA_FROM_STUDENT_SIDE

DROP VIEW VW_SHOW_FEES_ALL_DATA_STUDENT_SIDE

DROP VIEW VW_SHOW_STAFF_ALL_DATA_FROM_STAFF

DROP VIEW VW_SHOW_COMPITITION_ALL_DATA_FROM_STAFF

DROP VIEW VW_SHOW_STUDENTS_ALL_DATA_FROM_STAFF

DROP VIEW VW_SHOW_RESULT_ALL_DATA_FROM_STAFF

DROP VIEW VW_SHOW_EXIBITION_ALL_DATA_FROM_MANAGER_SIDE

DROP VIEW VW_SHOW_FEEDBACK_ALL_DATA

DROP VIEW VW_SHOW_FEES_DEFAULTER_ALL_DATA
--