//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMIN_LOGIN_MODEL
    {
        public int AD_ID { get; set; }
        public string AD_NAME { get; set; }
        [Required(ErrorMessage = "Password must be required")]
       // [RegularExpression(@"(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", ErrorMessage = "Inavlid Password")]
        [DataType(DataType.Password)]
        public string AD_PASSWORD { get; set; }
        public string AD_PROFILE { get; set; }
    }
}
