//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COMPITITION_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPITITION_MODEL()
        {
            this.RESULTs = new HashSet<RESULT_MODEL>();
            this.WORK_OF_COMPITITION = new HashSet<WORK_OF_COMPITITION_MODEL>();
        }
    
        public int COM_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string COM_NAME { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime COM_START_DATE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime COM_END_DATE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public int COM_STF_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULT_MODEL> RESULTs { get; set; }
        public virtual STAFF_LOGIN_MODEL STAFF_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_OF_COMPITITION_MODEL> WORK_OF_COMPITITION { get; set; }
    }
}
