//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EXIBITION_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXIBITION_MODEL()
        {
            this.EXIBITION_ENTRIES = new HashSet<EXIBITION_ENTRIES_MODEL>();
        }
    
        public int EXB_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string EXB_NAME { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime EXB_START_DATE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime EXB_END_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXIBITION_ENTRIES_MODEL> EXIBITION_ENTRIES { get; set; }
    }
}
