//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REGISTRATION_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRATION_MODEL()
        {
            this.EXIBITION_ENTRIES = new HashSet<EXIBITION_ENTRIES_MODEL>();
            this.WORK_OF_COMPITITION = new HashSet<WORK_OF_COMPITITION_MODEL>();
        }
    
        public int REG_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public int REG_STDL_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public Nullable<int> REG_CR_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    
        public virtual COURS_MODEL COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXIBITION_ENTRIES_MODEL> EXIBITION_ENTRIES { get; set; }
        public virtual STUDENT_LOGIN_MODEL STUDENT_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_OF_COMPITITION_MODEL> WORK_OF_COMPITITION { get; set; }
    }
}
