//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STAFF_LOGIN_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF_LOGIN_MODEL()
        {
            this.ASSIGNEDs = new HashSet<ASSIGNED_MODEL>();
            this.COMPITITIONs = new HashSet<COMPITITION_MODEL>();
            this.STAFF_DETAILS = new HashSet<STAFF_DETAILS_MODEL>();
        }
    
        public int STF_ID { get; set; }
        public string STF_NAME { get; set; }
        [Required(ErrorMessage = "Password must be required")]
    //    [RegularExpression(@"(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", ErrorMessage = "Inavlid Password")]
        [DataType(DataType.Password)]
        public string STF_PASSWORD { get; set; }
        public string STF_PROFILE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSIGNED_MODEL> ASSIGNEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPITITION_MODEL> COMPITITIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAFF_DETAILS_MODEL> STAFF_DETAILS { get; set; }
    }
}
