//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STAFF_DETAILS_MODEL
    {
        public int STFD_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_EDUCATION { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_ADDRESS { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress]
        public string STFD_EMAIL { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_PHONE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime STFD_DATE_OF_BIRTH { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public Nullable<decimal> STFD_SALARY { get; set; }
    
        public virtual STAFF_LOGIN_MODEL STAFF_LOGIN { get; set; }
    }
}
