//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STUDENT_DETAILS_MODEL
    {
        public int SD_STDL_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STD_ADDRESS { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress]
        public string STD_EMAIL { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STD_PHONE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime STD_DATE_OF_BIRTH { get; set; }
    
        public virtual STUDENT_LOGIN_MODEL STUDENT_LOGIN { get; set; }
    }
}
