//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS_MODEL
    {
        public int COM_ID { get; set; }
        public string COM_NAME { get; set; }
        public System.DateTime COM_START_DATE { get; set; }
        public System.DateTime COM_END_DATE { get; set; }
        public int COM_STF_ID { get; set; }
        public string STF_NAME { get; set; }
        public int CR_ID { get; set; }
        public string CR_NAME { get; set; }
    }
}
