//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class VW_SHOW_STAFF_ALL_DETIALS_MODEL
    {
        public int STF_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STF_NAME { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [RegularExpression(@"^.*(?=.{6,18})(?=.*\d)(?=.*[A-Za-z])(?=.*[@%&#]{0,}).*$",ErrorMessage = "Invalid Format for Password")]
        public string STF_PASSWORD { get; set; }
        public string STF_PROFILE { get; set; }
        public int STFD_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_EDUCATION { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_ADDRESS { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress]
        public string STFD_EMAIL { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STFD_PHONE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime STFD_DATE_OF_BIRTH { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public Nullable<decimal> STFD_SALARY { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
