//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class VW_SHOW_STUDENTS_ALL_DETIALS_MODEL
    {
        public int STDL_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STDL_NAME { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [RegularExpression(@"^.*(?=.{6,18})(?=.*\d)(?=.*[A-Za-z])(?=.*[@%&#]{0,}).*$", ErrorMessage = "Invalid Format for Password")]
        public string STDL_PASSWORD { get; set; }
        public string STDL_PROFILE { get; set; }
        public int SD_STDL_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STD_ADDRESS { get; set; }
        [Required(ErrorMessage = "Email Required")]
        [EmailAddress]
        public string STD_EMAIL { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string STD_PHONE { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        [DataType(DataType.Date)]
        public System.DateTime STD_DATE_OF_BIRTH { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
