//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class WORK_OF_COMPITITION_MODEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORK_OF_COMPITITION_MODEL()
        {
            this.RESULT_ENTRIES = new HashSet<RESULT_ENTRIES_MODEL>();
        }
    
        public int WOC_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public int WOC_REG_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public int WOC_COM_ID { get; set; }
        [Required(ErrorMessage = "Feild Required")]
        public string WOC_WORK { get; set; }
    
        public virtual COMPITITION_MODEL COMPITITION { get; set; }
        public virtual REGISTRATION_MODEL REGISTRATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULT_ENTRIES_MODEL> RESULT_ENTRIES { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
