//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_INSTITUTE_OF_FINE_ARTSEntities : DbContext
    {
        public DB_INSTITUTE_OF_FINE_ARTSEntities()
            : base("name=DB_INSTITUTE_OF_FINE_ARTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_LOGIN> ADMIN_LOGIN { get; set; }
        public virtual DbSet<ASSIGNED> ASSIGNEDs { get; set; }
        public virtual DbSet<COMPITITION> COMPITITIONs { get; set; }
        public virtual DbSet<COURS> COURSES { get; set; }
        public virtual DbSet<EXIBITION> EXIBITIONs { get; set; }
        public virtual DbSet<REGISTRATION> REGISTRATIONs { get; set; }
        public virtual DbSet<RESULT> RESULTs { get; set; }
        public virtual DbSet<STAFF_LOGIN> STAFF_LOGIN { get; set; }
        public virtual DbSet<STUDENT_LOGIN> STUDENT_LOGIN { get; set; }
        public virtual DbSet<WORK_OF_COMPITITION> WORK_OF_COMPITITION { get; set; }
        public virtual DbSet<EXIBITION_ENTRIES> EXIBITION_ENTRIES { get; set; }
        public virtual DbSet<RESULT_ENTRIES> RESULT_ENTRIES { get; set; }
        public virtual DbSet<STAFF_DETAILS> STAFF_DETAILS { get; set; }
        public virtual DbSet<STUDENT_DETAILS> STUDENT_DETAILS { get; set; }
        public virtual DbSet<VW_SHOW_COMPITITION_ALL_DATA> VW_SHOW_COMPITITION_ALL_DATA { get; set; }
        public virtual DbSet<VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS> VW_SHOW_COMPITITION_DETAILS_TO_STUDENTS { get; set; }
        public virtual DbSet<VW_SHOW_RESULT_ALL_DATA> VW_SHOW_RESULT_ALL_DATA { get; set; }
        public virtual DbSet<VW_SHOW_RESULT_CARD_DETIALS> VW_SHOW_RESULT_CARD_DETIALS { get; set; }
        public virtual DbSet<VW_SHOW_STAFF_ALL_DATA> VW_SHOW_STAFF_ALL_DATA { get; set; }
        public virtual DbSet<VW_SHOW_STAFF_ALL_DETIALS> VW_SHOW_STAFF_ALL_DETIALS { get; set; }
        public virtual DbSet<VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE> VW_SHOW_STUDENT_ALL_DATA_FROM_SUDENT_SIDE { get; set; }
        public virtual DbSet<VW_SHOW_STUDENTS_ALL_DATA> VW_SHOW_STUDENTS_ALL_DATA { get; set; }
        public virtual DbSet<VW_SHOW_STUDENTS_ALL_DETIALS> VW_SHOW_STUDENTS_ALL_DETIALS { get; set; }
        public virtual DbSet<VW_SHOW_ALL_EXIBITION_DATA> VW_SHOW_ALL_EXIBITION_DATA { get; set; }
    }
}
