//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRATION()
        {
            this.EXIBITION_ENTRIES = new HashSet<EXIBITION_ENTRIES>();
            this.WORK_OF_COMPITITION = new HashSet<WORK_OF_COMPITITION>();
        }
    
        public int REG_ID { get; set; }
        public int REG_STDL_ID { get; set; }
        public Nullable<int> REG_CR_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    
        public virtual COURS COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXIBITION_ENTRIES> EXIBITION_ENTRIES { get; set; }
        public virtual STUDENT_LOGIN STUDENT_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_OF_COMPITITION> WORK_OF_COMPITITION { get; set; }
    }
}
