//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts_Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SHOW_ALL_EXIBITION_DATA
    {
        public int EXB_EN_EXB_ID { get; set; }
        public int EXB_EN_RES_ID { get; set; }
        public decimal PRICE { get; set; }
        public int EXB_ID { get; set; }
        public string EXB_NAME { get; set; }
        public System.DateTime EXB_START_DATE { get; set; }
        public System.DateTime EXB_END_DATE { get; set; }
        public string WOC_WORK { get; set; }
        public string STDL_NAME { get; set; }
        public string STDL_PROFILE { get; set; }
        public string STD_EMAIL { get; set; }
    }
}
