//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPITITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPITITION()
        {
            this.RESULTs = new HashSet<RESULT>();
            this.WORK_OF_COMPITITION = new HashSet<WORK_OF_COMPITITION>();
        }
    
        public int COM_ID { get; set; }
        public string COM_NAME { get; set; }
        public System.DateTime COM_START_DATE { get; set; }
        public System.DateTime COM_END_DATE { get; set; }
        public int COM_STF_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULT> RESULTs { get; set; }
        public virtual STAFF_LOGIN STAFF_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_OF_COMPITITION> WORK_OF_COMPITITION { get; set; }
    }
}
