//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXIBITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXIBITION()
        {
            this.EXIBITION_ENTRIES = new HashSet<EXIBITION_ENTRIES>();
        }
    
        public int EXB_ID { get; set; }
        public string EXB_NAME { get; set; }
        public System.DateTime EXB_START_DATE { get; set; }
        public System.DateTime EXB_END_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXIBITION_ENTRIES> EXIBITION_ENTRIES { get; set; }
    }
}
