//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_LOGIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_LOGIN()
        {
            this.REGISTRATIONs = new HashSet<REGISTRATION>();
            this.STUDENT_DETAILS = new HashSet<STUDENT_DETAILS>();
        }
    
        public int STDL_ID { get; set; }
        public string STDL_NAME { get; set; }
        public string STDL_PASSWORD { get; set; }
        public string STDL_PROFILE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRATION> REGISTRATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_DETAILS> STUDENT_DETAILS { get; set; }
    }
}
