//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXIBITION
    {
        public int EXB_ID { get; set; }
        public string EXB_NAME { get; set; }
        public System.DateTime EXB_START_DATE { get; set; }
        public System.DateTime EXB_END_DATE { get; set; }
    }
}
