//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REGISTRATION
    {
        public int REG_ID { get; set; }
        public int REG_STDL_ID { get; set; }
        public Nullable<int> REG_CR_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
    }
}
