//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class VW_SHOW_STAFF_ALL_DETIALS
    {
        public int STF_ID { get; set; }
        public string STF_NAME { get; set; }
        public string STF_PASSWORD { get; set; }
        public string STF_PROFILE { get; set; }
        public int STFD_ID { get; set; }
        public string STFD_EDUCATION { get; set; }
        public string STFD_ADDRESS { get; set; }
        public string STFD_EMAIL { get; set; }
        public string STFD_PHONE { get; set; }
        public System.DateTime STFD_DATE_OF_BIRTH { get; set; }
        public Nullable<decimal> STFD_SALARY { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
