//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WORK_OF_COMPITITION
    {
        public int WOC_ID { get; set; }
        public int WOC_REG_ID { get; set; }
        public int WOC_COM_ID { get; set; }
        public string WOC_WORK { get; set; }
    }
}
